// Code generated by fastssz. DO NOT EDIT.
// Hash: 7daa53d28a846e39be4aa9869ee579d8211c462ddeaab8f1af1f411c8f7b7021
package spec

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Blocks object
func (b *Blocks) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the Blocks object to a target array
func (b *Blocks) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(16)

	// Field (0) 'HeadBlockNumber'
	dst = ssz.MarshalUint64(dst, b.HeadBlockNumber)

	// Field (1) 'BlockCount'
	dst = ssz.MarshalUint32(dst, b.BlockCount)

	// Offset (2) 'Payload'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(b.Payload); ii++ {
		offset += 4
		offset += b.Payload[ii].SizeSSZ()
	}

	// Field (2) 'Payload'
	if len(b.Payload) > 2000000 {
		err = ssz.ErrListTooBig
		return
	}
	{
		offset = 4 * len(b.Payload)
		for ii := 0; ii < len(b.Payload); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += b.Payload[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(b.Payload); ii++ {
		if dst, err = b.Payload[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the Blocks object
func (b *Blocks) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 16 {
		return ssz.ErrSize
	}

	tail := buf
	var o2 uint64

	// Field (0) 'HeadBlockNumber'
	b.HeadBlockNumber = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'BlockCount'
	b.BlockCount = ssz.UnmarshallUint32(buf[8:12])

	// Offset (2) 'Payload'
	if o2 = ssz.ReadOffset(buf[12:16]); o2 > size {
		return ssz.ErrOffset
	}

	if o2 < 16 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (2) 'Payload'
	{
		buf = tail[o2:]
		num, err := ssz.DecodeDynamicLength(buf, 2000000)
		if err != nil {
			return err
		}
		b.Payload = make([]*ExecutionPayload, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if b.Payload[indx] == nil {
				b.Payload[indx] = new(ExecutionPayload)
			}
			if err = b.Payload[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Blocks object
func (b *Blocks) SizeSSZ() (size int) {
	size = 16

	// Field (2) 'Payload'
	for ii := 0; ii < len(b.Payload); ii++ {
		size += 4
		size += b.Payload[ii].SizeSSZ()
	}

	return
}

// HashTreeRoot ssz hashes the Blocks object
func (b *Blocks) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the Blocks object with a hasher
func (b *Blocks) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'HeadBlockNumber'
	hh.PutUint64(b.HeadBlockNumber)

	// Field (1) 'BlockCount'
	hh.PutUint32(b.BlockCount)

	// Field (2) 'Payload'
	{
		subIndx := hh.Index()
		num := uint64(len(b.Payload))
		if num > 2000000 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.Payload {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 2000000)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ExecutionHeader object
func (e *ExecutionHeader) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(e)
}

// MarshalSSZTo ssz marshals the ExecutionHeader object to a target array
func (e *ExecutionHeader) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(576)

	// Field (0) 'ParentHash'
	if len(e.ParentHash) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, e.ParentHash...)

	// Field (1) 'UncleHash'
	if len(e.UncleHash) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, e.UncleHash...)

	// Field (2) 'FeeRecipient'
	if len(e.FeeRecipient) != 20 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, e.FeeRecipient...)

	// Field (3) 'StateRoot'
	if len(e.StateRoot) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, e.StateRoot...)

	// Field (4) 'TxHash'
	if len(e.TxHash) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, e.TxHash...)

	// Field (5) 'ReceiptsRoot'
	if len(e.ReceiptsRoot) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, e.ReceiptsRoot...)

	// Field (6) 'LogsBloom'
	if len(e.LogsBloom) != 256 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, e.LogsBloom...)

	// Field (7) 'PrevRandao'
	if len(e.PrevRandao) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, e.PrevRandao...)

	// Field (8) 'BlockNumber'
	dst = ssz.MarshalUint64(dst, e.BlockNumber)

	// Field (9) 'GasLimit'
	dst = ssz.MarshalUint64(dst, e.GasLimit)

	// Field (10) 'GasUsed'
	dst = ssz.MarshalUint64(dst, e.GasUsed)

	// Field (11) 'Timestamp'
	dst = ssz.MarshalUint64(dst, e.Timestamp)

	// Offset (12) 'ExtraData'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(e.ExtraData)

	// Field (13) 'BaseFeePerGas'
	if len(e.BaseFeePerGas) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, e.BaseFeePerGas...)

	// Field (14) 'MixDigest'
	if len(e.MixDigest) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, e.MixDigest...)

	// Field (15) 'Nonce'
	if len(e.Nonce) != 8 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, e.Nonce...)

	// Field (12) 'ExtraData'
	if len(e.ExtraData) > 32 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, e.ExtraData...)

	return
}

// UnmarshalSSZ ssz unmarshals the ExecutionHeader object
func (e *ExecutionHeader) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 576 {
		return ssz.ErrSize
	}

	tail := buf
	var o12 uint64

	// Field (0) 'ParentHash'
	if cap(e.ParentHash) == 0 {
		e.ParentHash = make([]byte, 0, len(buf[0:32]))
	}
	e.ParentHash = append(e.ParentHash, buf[0:32]...)

	// Field (1) 'UncleHash'
	if cap(e.UncleHash) == 0 {
		e.UncleHash = make([]byte, 0, len(buf[32:64]))
	}
	e.UncleHash = append(e.UncleHash, buf[32:64]...)

	// Field (2) 'FeeRecipient'
	if cap(e.FeeRecipient) == 0 {
		e.FeeRecipient = make([]byte, 0, len(buf[64:84]))
	}
	e.FeeRecipient = append(e.FeeRecipient, buf[64:84]...)

	// Field (3) 'StateRoot'
	if cap(e.StateRoot) == 0 {
		e.StateRoot = make([]byte, 0, len(buf[84:116]))
	}
	e.StateRoot = append(e.StateRoot, buf[84:116]...)

	// Field (4) 'TxHash'
	if cap(e.TxHash) == 0 {
		e.TxHash = make([]byte, 0, len(buf[116:148]))
	}
	e.TxHash = append(e.TxHash, buf[116:148]...)

	// Field (5) 'ReceiptsRoot'
	if cap(e.ReceiptsRoot) == 0 {
		e.ReceiptsRoot = make([]byte, 0, len(buf[148:180]))
	}
	e.ReceiptsRoot = append(e.ReceiptsRoot, buf[148:180]...)

	// Field (6) 'LogsBloom'
	if cap(e.LogsBloom) == 0 {
		e.LogsBloom = make([]byte, 0, len(buf[180:436]))
	}
	e.LogsBloom = append(e.LogsBloom, buf[180:436]...)

	// Field (7) 'PrevRandao'
	if cap(e.PrevRandao) == 0 {
		e.PrevRandao = make([]byte, 0, len(buf[436:468]))
	}
	e.PrevRandao = append(e.PrevRandao, buf[436:468]...)

	// Field (8) 'BlockNumber'
	e.BlockNumber = ssz.UnmarshallUint64(buf[468:476])

	// Field (9) 'GasLimit'
	e.GasLimit = ssz.UnmarshallUint64(buf[476:484])

	// Field (10) 'GasUsed'
	e.GasUsed = ssz.UnmarshallUint64(buf[484:492])

	// Field (11) 'Timestamp'
	e.Timestamp = ssz.UnmarshallUint64(buf[492:500])

	// Offset (12) 'ExtraData'
	if o12 = ssz.ReadOffset(buf[500:504]); o12 > size {
		return ssz.ErrOffset
	}

	if o12 < 576 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (13) 'BaseFeePerGas'
	if cap(e.BaseFeePerGas) == 0 {
		e.BaseFeePerGas = make([]byte, 0, len(buf[504:536]))
	}
	e.BaseFeePerGas = append(e.BaseFeePerGas, buf[504:536]...)

	// Field (14) 'MixDigest'
	if cap(e.MixDigest) == 0 {
		e.MixDigest = make([]byte, 0, len(buf[536:568]))
	}
	e.MixDigest = append(e.MixDigest, buf[536:568]...)

	// Field (15) 'Nonce'
	if cap(e.Nonce) == 0 {
		e.Nonce = make([]byte, 0, len(buf[568:576]))
	}
	e.Nonce = append(e.Nonce, buf[568:576]...)

	// Field (12) 'ExtraData'
	{
		buf = tail[o12:]
		if len(buf) > 32 {
			return ssz.ErrBytesLength
		}
		if cap(e.ExtraData) == 0 {
			e.ExtraData = make([]byte, 0, len(buf))
		}
		e.ExtraData = append(e.ExtraData, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ExecutionHeader object
func (e *ExecutionHeader) SizeSSZ() (size int) {
	size = 576

	// Field (12) 'ExtraData'
	size += len(e.ExtraData)

	return
}

// HashTreeRoot ssz hashes the ExecutionHeader object
func (e *ExecutionHeader) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(e)
}

// HashTreeRootWith ssz hashes the ExecutionHeader object with a hasher
func (e *ExecutionHeader) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'ParentHash'
	if len(e.ParentHash) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	hh.PutBytes(e.ParentHash)

	// Field (1) 'UncleHash'
	if len(e.UncleHash) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	hh.PutBytes(e.UncleHash)

	// Field (2) 'FeeRecipient'
	if len(e.FeeRecipient) != 20 {
		err = ssz.ErrBytesLength
		return
	}
	hh.PutBytes(e.FeeRecipient)

	// Field (3) 'StateRoot'
	if len(e.StateRoot) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	hh.PutBytes(e.StateRoot)

	// Field (4) 'TxHash'
	if len(e.TxHash) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	hh.PutBytes(e.TxHash)

	// Field (5) 'ReceiptsRoot'
	if len(e.ReceiptsRoot) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	hh.PutBytes(e.ReceiptsRoot)

	// Field (6) 'LogsBloom'
	if len(e.LogsBloom) != 256 {
		err = ssz.ErrBytesLength
		return
	}
	hh.PutBytes(e.LogsBloom)

	// Field (7) 'PrevRandao'
	if len(e.PrevRandao) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	hh.PutBytes(e.PrevRandao)

	// Field (8) 'BlockNumber'
	hh.PutUint64(e.BlockNumber)

	// Field (9) 'GasLimit'
	hh.PutUint64(e.GasLimit)

	// Field (10) 'GasUsed'
	hh.PutUint64(e.GasUsed)

	// Field (11) 'Timestamp'
	hh.PutUint64(e.Timestamp)

	// Field (12) 'ExtraData'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(e.ExtraData))
		if byteLen > 32 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.PutBytes(e.ExtraData)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (32+31)/32)
	}

	// Field (13) 'BaseFeePerGas'
	if len(e.BaseFeePerGas) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	hh.PutBytes(e.BaseFeePerGas)

	// Field (14) 'MixDigest'
	if len(e.MixDigest) != 32 {
		err = ssz.ErrBytesLength
		return
	}
	hh.PutBytes(e.MixDigest)

	// Field (15) 'Nonce'
	if len(e.Nonce) != 8 {
		err = ssz.ErrBytesLength
		return
	}
	hh.PutBytes(e.Nonce)

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ExecutionPayload object
func (e *ExecutionPayload) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(e)
}

// MarshalSSZTo ssz marshals the ExecutionPayload object to a target array
func (e *ExecutionPayload) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(16)

	// Offset (0) 'Header'
	dst = ssz.WriteOffset(dst, offset)
	if e.Header == nil {
		e.Header = new(ExecutionHeader)
	}
	offset += e.Header.SizeSSZ()

	// Offset (1) 'Transactions'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(e.Transactions); ii++ {
		offset += 4
		offset += len(e.Transactions[ii])
	}

	// Offset (2) 'Uncles'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(e.Uncles); ii++ {
		offset += 4
		offset += e.Uncles[ii].SizeSSZ()
	}

	// Offset (3) 'Receipts'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(e.Receipts); ii++ {
		offset += 4
		offset += e.Receipts[ii].SizeSSZ()
	}

	// Field (0) 'Header'
	if dst, err = e.Header.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'Transactions'
	if len(e.Transactions) > 1048576 {
		err = ssz.ErrListTooBig
		return
	}
	{
		offset = 4 * len(e.Transactions)
		for ii := 0; ii < len(e.Transactions); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(e.Transactions[ii])
		}
	}
	for ii := 0; ii < len(e.Transactions); ii++ {
		if len(e.Transactions[ii]) > 1073741824 {
			err = ssz.ErrBytesLength
			return
		}
		dst = append(dst, e.Transactions[ii]...)
	}

	// Field (2) 'Uncles'
	if len(e.Uncles) > 6040 {
		err = ssz.ErrListTooBig
		return
	}
	{
		offset = 4 * len(e.Uncles)
		for ii := 0; ii < len(e.Uncles); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += e.Uncles[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(e.Uncles); ii++ {
		if dst, err = e.Uncles[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (3) 'Receipts'
	if len(e.Receipts) > 4194452 {
		err = ssz.ErrListTooBig
		return
	}
	{
		offset = 4 * len(e.Receipts)
		for ii := 0; ii < len(e.Receipts); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += e.Receipts[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(e.Receipts); ii++ {
		if dst, err = e.Receipts[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the ExecutionPayload object
func (e *ExecutionPayload) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 16 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o1, o2, o3 uint64

	// Offset (0) 'Header'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 < 16 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (1) 'Transactions'
	if o1 = ssz.ReadOffset(buf[4:8]); o1 > size || o0 > o1 {
		return ssz.ErrOffset
	}

	// Offset (2) 'Uncles'
	if o2 = ssz.ReadOffset(buf[8:12]); o2 > size || o1 > o2 {
		return ssz.ErrOffset
	}

	// Offset (3) 'Receipts'
	if o3 = ssz.ReadOffset(buf[12:16]); o3 > size || o2 > o3 {
		return ssz.ErrOffset
	}

	// Field (0) 'Header'
	{
		buf = tail[o0:o1]
		if e.Header == nil {
			e.Header = new(ExecutionHeader)
		}
		if err = e.Header.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (1) 'Transactions'
	{
		buf = tail[o1:o2]
		num, err := ssz.DecodeDynamicLength(buf, 1048576)
		if err != nil {
			return err
		}
		e.Transactions = make([][]byte, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 1073741824 {
				return ssz.ErrBytesLength
			}
			if cap(e.Transactions[indx]) == 0 {
				e.Transactions[indx] = make([]byte, 0, len(buf))
			}
			e.Transactions[indx] = append(e.Transactions[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (2) 'Uncles'
	{
		buf = tail[o2:o3]
		num, err := ssz.DecodeDynamicLength(buf, 6040)
		if err != nil {
			return err
		}
		e.Uncles = make([]*ExecutionHeader, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if e.Uncles[indx] == nil {
				e.Uncles[indx] = new(ExecutionHeader)
			}
			if err = e.Uncles[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (3) 'Receipts'
	{
		buf = tail[o3:]
		num, err := ssz.DecodeDynamicLength(buf, 4194452)
		if err != nil {
			return err
		}
		e.Receipts = make([]*ReceiptPayload, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if e.Receipts[indx] == nil {
				e.Receipts[indx] = new(ReceiptPayload)
			}
			if err = e.Receipts[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ExecutionPayload object
func (e *ExecutionPayload) SizeSSZ() (size int) {
	size = 16

	// Field (0) 'Header'
	if e.Header == nil {
		e.Header = new(ExecutionHeader)
	}
	size += e.Header.SizeSSZ()

	// Field (1) 'Transactions'
	for ii := 0; ii < len(e.Transactions); ii++ {
		size += 4
		size += len(e.Transactions[ii])
	}

	// Field (2) 'Uncles'
	for ii := 0; ii < len(e.Uncles); ii++ {
		size += 4
		size += e.Uncles[ii].SizeSSZ()
	}

	// Field (3) 'Receipts'
	for ii := 0; ii < len(e.Receipts); ii++ {
		size += 4
		size += e.Receipts[ii].SizeSSZ()
	}

	return
}

// HashTreeRoot ssz hashes the ExecutionPayload object
func (e *ExecutionPayload) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(e)
}

// HashTreeRootWith ssz hashes the ExecutionPayload object with a hasher
func (e *ExecutionPayload) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Header'
	if err = e.Header.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Transactions'
	{
		subIndx := hh.Index()
		num := uint64(len(e.Transactions))
		if num > 1048576 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range e.Transactions {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 1073741824 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (1073741824+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 1048576)
	}

	// Field (2) 'Uncles'
	{
		subIndx := hh.Index()
		num := uint64(len(e.Uncles))
		if num > 6040 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range e.Uncles {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 6040)
	}

	// Field (3) 'Receipts'
	{
		subIndx := hh.Index()
		num := uint64(len(e.Receipts))
		if num > 4194452 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range e.Receipts {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 4194452)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the ReceiptPayload object
func (r *ReceiptPayload) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(r)
}

// MarshalSSZTo ssz marshals the ReceiptPayload object to a target array
func (r *ReceiptPayload) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(24)

	// Offset (0) 'PostState'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(r.PostState)

	// Field (1) 'Status'
	dst = ssz.MarshalUint64(dst, r.Status)

	// Field (2) 'CumulativeGasUsed'
	dst = ssz.MarshalUint64(dst, r.CumulativeGasUsed)

	// Offset (3) 'Logs'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(r.Logs); ii++ {
		offset += 4
		offset += r.Logs[ii].SizeSSZ()
	}

	// Field (0) 'PostState'
	if len(r.PostState) > 32 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, r.PostState...)

	// Field (3) 'Logs'
	if len(r.Logs) > 4194452 {
		err = ssz.ErrListTooBig
		return
	}
	{
		offset = 4 * len(r.Logs)
		for ii := 0; ii < len(r.Logs); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += r.Logs[ii].SizeSSZ()
		}
	}
	for ii := 0; ii < len(r.Logs); ii++ {
		if dst, err = r.Logs[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}
	return
}

// UnmarshalSSZ ssz unmarshals the ReceiptPayload object
func (r *ReceiptPayload) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 24 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o3 uint64

	// Offset (0) 'PostState'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 < 24 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Status'
	r.Status = ssz.UnmarshallUint64(buf[4:12])

	// Field (2) 'CumulativeGasUsed'
	r.CumulativeGasUsed = ssz.UnmarshallUint64(buf[12:20])

	// Offset (3) 'Logs'
	if o3 = ssz.ReadOffset(buf[20:24]); o3 > size || o0 > o3 {
		return ssz.ErrOffset
	}

	// Field (0) 'PostState'
	{
		buf = tail[o0:o3]
		if len(buf) > 32 {
			return ssz.ErrBytesLength
		}
		if cap(r.PostState) == 0 {
			r.PostState = make([]byte, 0, len(buf))
		}
		r.PostState = append(r.PostState, buf...)
	}

	// Field (3) 'Logs'
	{
		buf = tail[o3:]
		num, err := ssz.DecodeDynamicLength(buf, 4194452)
		if err != nil {
			return err
		}
		r.Logs = make([]*LogPayload, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if r.Logs[indx] == nil {
				r.Logs[indx] = new(LogPayload)
			}
			if err = r.Logs[indx].UnmarshalSSZ(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ReceiptPayload object
func (r *ReceiptPayload) SizeSSZ() (size int) {
	size = 24

	// Field (0) 'PostState'
	size += len(r.PostState)

	// Field (3) 'Logs'
	for ii := 0; ii < len(r.Logs); ii++ {
		size += 4
		size += r.Logs[ii].SizeSSZ()
	}

	return
}

// HashTreeRoot ssz hashes the ReceiptPayload object
func (r *ReceiptPayload) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(r)
}

// HashTreeRootWith ssz hashes the ReceiptPayload object with a hasher
func (r *ReceiptPayload) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'PostState'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(r.PostState))
		if byteLen > 32 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.PutBytes(r.PostState)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (32+31)/32)
	}

	// Field (1) 'Status'
	hh.PutUint64(r.Status)

	// Field (2) 'CumulativeGasUsed'
	hh.PutUint64(r.CumulativeGasUsed)

	// Field (3) 'Logs'
	{
		subIndx := hh.Index()
		num := uint64(len(r.Logs))
		if num > 4194452 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range r.Logs {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 4194452)
	}

	hh.Merkleize(indx)
	return
}

// MarshalSSZ ssz marshals the LogPayload object
func (l *LogPayload) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(l)
}

// MarshalSSZTo ssz marshals the LogPayload object to a target array
func (l *LogPayload) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(28)

	// Field (0) 'Address'
	if len(l.Address) != 20 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, l.Address...)

	// Offset (1) 'Topics'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(l.Topics) * 32

	// Offset (2) 'Data'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(l.Data)

	// Field (1) 'Topics'
	if len(l.Topics) > 4 {
		err = ssz.ErrListTooBig
		return
	}
	for ii := 0; ii < len(l.Topics); ii++ {
		if len(l.Topics[ii]) != 32 {
			err = ssz.ErrBytesLength
			return
		}
		dst = append(dst, l.Topics[ii]...)
	}

	// Field (2) 'Data'
	if len(l.Data) > 4194304 {
		err = ssz.ErrBytesLength
		return
	}
	dst = append(dst, l.Data...)

	return
}

// UnmarshalSSZ ssz unmarshals the LogPayload object
func (l *LogPayload) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 28 {
		return ssz.ErrSize
	}

	tail := buf
	var o1, o2 uint64

	// Field (0) 'Address'
	if cap(l.Address) == 0 {
		l.Address = make([]byte, 0, len(buf[0:20]))
	}
	l.Address = append(l.Address, buf[0:20]...)

	// Offset (1) 'Topics'
	if o1 = ssz.ReadOffset(buf[20:24]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 < 28 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (2) 'Data'
	if o2 = ssz.ReadOffset(buf[24:28]); o2 > size || o1 > o2 {
		return ssz.ErrOffset
	}

	// Field (1) 'Topics'
	{
		buf = tail[o1:o2]
		num, err := ssz.DivideInt2(len(buf), 32, 4)
		if err != nil {
			return err
		}
		l.Topics = make([][]byte, num)
		for ii := 0; ii < num; ii++ {
			if cap(l.Topics[ii]) == 0 {
				l.Topics[ii] = make([]byte, 0, len(buf[ii*32:(ii+1)*32]))
			}
			l.Topics[ii] = append(l.Topics[ii], buf[ii*32:(ii+1)*32]...)
		}
	}

	// Field (2) 'Data'
	{
		buf = tail[o2:]
		if len(buf) > 4194304 {
			return ssz.ErrBytesLength
		}
		if cap(l.Data) == 0 {
			l.Data = make([]byte, 0, len(buf))
		}
		l.Data = append(l.Data, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the LogPayload object
func (l *LogPayload) SizeSSZ() (size int) {
	size = 28

	// Field (1) 'Topics'
	size += len(l.Topics) * 32

	// Field (2) 'Data'
	size += len(l.Data)

	return
}

// HashTreeRoot ssz hashes the LogPayload object
func (l *LogPayload) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(l)
}

// HashTreeRootWith ssz hashes the LogPayload object with a hasher
func (l *LogPayload) HashTreeRootWith(hh *ssz.Hasher) (err error) {
	indx := hh.Index()

	// Field (0) 'Address'
	if len(l.Address) != 20 {
		err = ssz.ErrBytesLength
		return
	}
	hh.PutBytes(l.Address)

	// Field (1) 'Topics'
	{
		if len(l.Topics) > 4 {
			err = ssz.ErrListTooBig
			return
		}
		subIndx := hh.Index()
		for _, i := range l.Topics {
			if len(i) != 32 {
				err = ssz.ErrBytesLength
				return
			}
			hh.Append(i)
		}
		numItems := uint64(len(l.Topics))
		hh.MerkleizeWithMixin(subIndx, numItems, ssz.CalculateLimit(4, numItems, 32))
	}

	// Field (2) 'Data'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(l.Data))
		if byteLen > 4194304 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.PutBytes(l.Data)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (4194304+31)/32)
	}

	hh.Merkleize(indx)
	return
}
